server:
  port: 9090

spring:
  application:
    name: = ebook-store

  datasource:
    url: jdbc:postgresql://localhost:5432/ebookstoredb
    username: postgres
    password: root


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update